import { Router } from 'express';
import bcrypt from 'bcryptjs';
import pool from '../db.mjs';
import { signToken } from '../auth.mjs';

const router = Router();

let ensureUsersTablePromise = null;

function normalizeRoleInput(value) {
  const normalized = String(value ?? '').trim().toLowerCase();
  if (normalized === 'firm' || normalized === 'company' || normalized === 'firma' || normalized === 'unternehmen' || normalized === 'betrieb' || normalized === 'employer') {
    return 'firm';
  }
  return 'student';
}

async function ensureUsersTable() {
  if (!ensureUsersTablePromise) {
    ensureUsersTablePromise = pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(320) NOT NULL UNIQUE,
        password TEXT NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'firm')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `).catch((err) => {
      ensureUsersTablePromise = null;
      throw err;
    });
  }

  await ensureUsersTablePromise;
}

ensureUsersTable().catch((err) => console.error('[users] Tabelle konnte nicht angelegt werden:', err.message));

// POST /api/auth/register
router.post('/register', async (req, res) => {
  const { email, password, role } = req.body ?? {};

  if (!email || !password) {
    return res.status(400).json({ error: 'E-Mail und Passwort sind erforderlich.' });
  }

  const normalizedEmail = String(email).toLowerCase().trim();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail)) {
    return res.status(400).json({ error: 'Ungueltige E-Mail-Adresse.' });
  }

  if (String(password).length < 6) {
    return res.status(400).json({ error: 'Passwort muss mindestens 6 Zeichen haben.' });
  }

  const normalizedRole = normalizeRoleInput(role);

  try {
    await ensureUsersTable();

    const existing = await pool.query('SELECT id FROM users WHERE email = $1', [normalizedEmail]);
    if (existing.rowCount > 0) {
      return res.status(409).json({ error: 'Diese E-Mail ist bereits registriert.' });
    }

    const hash = await bcrypt.hash(String(password), 12);
    const result = await pool.query(
      'INSERT INTO users (email, password, role) VALUES ($1, $2, $3) RETURNING id, email, role, created_at',
      [normalizedEmail, hash, normalizedRole]
    );

    const user = result.rows[0];
    const token = signToken({ id: user.id, email: user.email, role: user.role });

    return res.status(201).json({
      token,
      user: { id: user.id, email: user.email, role: user.role },
    });
  } catch (err) {
    console.error('[register]', err.message);
    return res.status(500).json({ error: 'Registrierung fehlgeschlagen. Bitte erneut versuchen.' });
  }
});

// POST /api/auth/login
router.post('/login', async (req, res) => {
  const { email, password } = req.body ?? {};

  if (!email || !password) {
    return res.status(400).json({ error: 'E-Mail und Passwort sind erforderlich.' });
  }

  const normalizedEmail = String(email).toLowerCase().trim();

  try {
    await ensureUsersTable();

    const result = await pool.query(
      'SELECT id, email, password, role FROM users WHERE email = $1',
      [normalizedEmail]
    );

    if (result.rowCount === 0) {
      return res.status(401).json({ error: 'E-Mail oder Passwort falsch.' });
    }

    const user = result.rows[0];
    const valid = await bcrypt.compare(String(password), user.password);

    if (!valid) {
      return res.status(401).json({ error: 'E-Mail oder Passwort falsch.' });
    }

    const token = signToken({ id: user.id, email: user.email, role: user.role });

    return res.json({
      token,
      user: { id: user.id, email: user.email, role: user.role },
    });
  } catch (err) {
    console.error('[login]', err.message);
    return res.status(500).json({ error: 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.' });
  }
});

// GET /api/auth/me
router.get('/me', async (req, res) => {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;

  if (!token) {
    return res.status(401).json({ error: 'Nicht angemeldet.' });
  }

  try {
    await ensureUsersTable();

    const { verifyToken } = await import('../auth.mjs');
    const payload = verifyToken(token);
    const result = await pool.query('SELECT id, email, role, created_at FROM users WHERE id = $1', [payload.id]);

    if (result.rowCount === 0) {
      return res.status(404).json({ error: 'Benutzer nicht gefunden.' });
    }

    return res.json({ user: result.rows[0] });
  } catch {
    return res.status(401).json({ error: 'Sitzung abgelaufen.' });
  }
});

// DELETE /api/auth/account  – löscht das eigene Konto (inkl. Kaskaden)
router.delete('/account', async (req, res) => {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;

  if (!token) {
    return res.status(401).json({ error: 'Nicht angemeldet.' });
  }

  try {
    const { verifyToken } = await import('../auth.mjs');
    const payload = verifyToken(token);

    await ensureUsersTable();
    const result = await pool.query('DELETE FROM users WHERE id = $1 RETURNING id', [payload.id]);

    if (result.rowCount === 0) {
      return res.status(404).json({ error: 'Benutzer nicht gefunden.' });
    }

    return res.status(204).end();
  } catch {
    return res.status(401).json({ error: 'Sitzung abgelaufen.' });
  }
});

export default router;
