import { Router } from 'express';
import bcrypt from 'bcryptjs';
import pool from '../db.mjs';
import { signToken } from '../auth.mjs';

const router = Router();

let ensureUsersTablePromise = null;
let usersColumnsCache = null;

const roleColumnCandidates = ['role', 'user_role', 'account_type', 'user_type', 'portal_role'];
const firmFlagColumnCandidates = ['is_firm', 'is_company', 'company_account'];

async function ensureUsersTable() {
  if (!ensureUsersTablePromise) {
    ensureUsersTablePromise = pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email VARCHAR(320) NOT NULL UNIQUE,
        password TEXT NOT NULL,
        role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'firm')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
      )
    `).catch((err) => {
      ensureUsersTablePromise = null;
      throw err;
    });
  }

  await ensureUsersTablePromise;
}

ensureUsersTable().catch((err) => console.error('[users] Tabelle konnte nicht angelegt werden:', err.message));

async function getUsersColumns() {
  if (usersColumnsCache) {
    return usersColumnsCache;
  }

  const result = await pool.query(
    `SELECT column_name
       FROM information_schema.columns
      WHERE table_catalog = current_database()
        AND table_schema = current_schema()
        AND table_name = 'users'`
  );

  usersColumnsCache = new Set(result.rows.map((row) => row.column_name));
  return usersColumnsCache;
}

function normalizeRole(value) {
  const normalized = String(value ?? '').toLowerCase().trim();
  if (!normalized) {
    return 'student';
  }

  const firmRoles = new Set(['firm', 'firma', 'company', 'unternehmen', 'betrieb', 'employer']);
  return firmRoles.has(normalized) ? 'firm' : 'student';
}

function resolveUserRole(userRow) {
  for (const column of roleColumnCandidates) {
    if (column in userRow && String(userRow[column] ?? '').trim() !== '') {
      return normalizeRole(userRow[column]);
    }
  }

  for (const column of firmFlagColumnCandidates) {
    if (column in userRow && userRow[column]) {
      return 'firm';
    }
  }

  return 'student';
}

// POST /api/auth/register
router.post('/register', async (req, res) => {
  const { email, password, role } = req.body ?? {};

  if (!email || !password) {
    return res.status(400).json({ error: 'E-Mail und Passwort sind erforderlich.' });
  }

  const normalizedEmail = String(email).toLowerCase().trim();
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalizedEmail)) {
    return res.status(400).json({ error: 'Ungueltige E-Mail-Adresse.' });
  }

  if (String(password).length < 6) {
    return res.status(400).json({ error: 'Passwort muss mindestens 6 Zeichen haben.' });
  }

  const normalizedRole = normalizeRole(role);

  try {
    await ensureUsersTable();
    const columns = await getUsersColumns();
    const roleColumn = roleColumnCandidates.find((column) => columns.has(column));
    const firmFlagColumn = firmFlagColumnCandidates.find((column) => columns.has(column));
    const hasCreatedAt = columns.has('created_at');

    const existing = await pool.query('SELECT id FROM users WHERE email = $1', [normalizedEmail]);
    if (existing.rowCount > 0) {
      return res.status(409).json({ error: 'Diese E-Mail ist bereits registriert.' });
    }

    const hash = await bcrypt.hash(String(password), 12);

    if (roleColumn) {
      await pool.query(
        `INSERT INTO users (email, password, ${roleColumn}) VALUES ($1, $2, $3)`,
        [normalizedEmail, hash, normalizedRole]
      );
    } else if (firmFlagColumn) {
      await pool.query(
        `INSERT INTO users (email, password, ${firmFlagColumn}) VALUES ($1, $2, $3)`,
        [normalizedEmail, hash, normalizedRole === 'firm']
      );
    } else {
      await pool.query('INSERT INTO users (email, password) VALUES ($1, $2)', [normalizedEmail, hash]);
    }

    const selectColumns = hasCreatedAt
      ? 'id, email, created_at, *'
      : 'id, email, *';
    const result = await pool.query(
      `SELECT ${selectColumns} FROM users WHERE email = $1 LIMIT 1`,
      [normalizedEmail]
    );

    const user = result.rows[0];
    const resolvedRole = resolveUserRole(user);
    const token = signToken({ id: user.id, email: user.email, role: resolvedRole });

    return res.status(201).json({
      token,
      user: { id: user.id, email: user.email, role: resolvedRole },
    });
  } catch (err) {
    console.error('[register]', err.message, err.code ? `(code: ${err.code})` : '');
    return res.status(500).json({ error: 'Registrierung fehlgeschlagen. Bitte erneut versuchen.' });
  }
});

// POST /api/auth/login
router.post('/login', async (req, res) => {
  const { email, password } = req.body ?? {};

  if (!email || !password) {
    return res.status(400).json({ error: 'E-Mail und Passwort sind erforderlich.' });
  }

  const normalizedEmail = String(email).toLowerCase().trim();

  try {
    await ensureUsersTable();

    const result = await pool.query(
      'SELECT * FROM users WHERE email = $1',
      [normalizedEmail]
    );

    if (result.rowCount === 0) {
      return res.status(401).json({ error: 'E-Mail oder Passwort falsch.' });
    }

    const user = result.rows[0];
    const valid = await bcrypt.compare(String(password), user.password);

    if (!valid) {
      return res.status(401).json({ error: 'E-Mail oder Passwort falsch.' });
    }

    const resolvedRole = resolveUserRole(user);
    const token = signToken({ id: user.id, email: user.email, role: resolvedRole });

    return res.json({
      token,
      user: { id: user.id, email: user.email, role: resolvedRole },
    });
  } catch (err) {
    console.error('[login]', err.message, err.code ? `(code: ${err.code})` : '');
    return res.status(500).json({ error: 'Anmeldung fehlgeschlagen. Bitte erneut versuchen.' });
  }
});

// GET /api/auth/me
router.get('/me', async (req, res) => {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.startsWith('Bearer ') ? authHeader.slice(7) : null;

  if (!token) {
    return res.status(401).json({ error: 'Nicht angemeldet.' });
  }

  try {
    await ensureUsersTable();

    const { verifyToken } = await import('../auth.mjs');
    const payload = verifyToken(token);
    const result = await pool.query('SELECT * FROM users WHERE id = $1', [payload.id]);

    if (result.rowCount === 0) {
      return res.status(404).json({ error: 'Benutzer nicht gefunden.' });
    }

    const user = result.rows[0];
    return res.json({
      user: {
        id: user.id,
        email: user.email,
        role: resolveUserRole(user),
        created_at: user.created_at ?? null,
      },
    });
  } catch {
    return res.status(401).json({ error: 'Sitzung abgelaufen.' });
  }
});

export default router;
