import { Router } from 'express';
import pool from '../db.mjs';
import { requireAuth } from '../auth.mjs';

const router = Router();

// Sicherstellen, dass die firm_profiles-Tabelle existiert
async function ensureTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(320) NOT NULL UNIQUE,
      password TEXT NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'firm')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS firm_profiles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      firmenname VARCHAR(200),
      stadt VARCHAR(200),
      plz VARCHAR(10),
      branche VARCHAR(200),
      ausbildungsberufe TEXT,
      match_umkreis INTEGER DEFAULT 25,
      beschreibung TEXT,
      website VARCHAR(500),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

ensureTable().catch((err) => console.error('[firm_profiles] Tabelle konnte nicht angelegt werden:', err.message));

// GET /api/firm/profile
router.get('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'firm') {
    return res.status(403).json({ error: 'Nur fuer Unternehmen zugaenglich.' });
  }

  try {
    await ensureTable();

    const result = await pool.query(
      'SELECT * FROM firm_profiles WHERE user_id = $1',
      [req.user.id]
    );
    return res.json({ profile: result.rows[0] ?? null });
  } catch (err) {
    console.error('[firm/profile GET]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht geladen werden.' });
  }
});

// PUT /api/firm/profile
router.put('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'firm') {
    return res.status(403).json({ error: 'Nur fuer Unternehmen zugaenglich.' });
  }

  const { firmenname, stadt, plz, branche, ausbildungsberufe, match_umkreis, beschreibung, website } = req.body ?? {};

  try {
    await ensureTable();

    const result = await pool.query(
      `INSERT INTO firm_profiles (user_id, firmenname, stadt, plz, branche, ausbildungsberufe, match_umkreis, beschreibung, website, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP)
       ON CONFLICT (user_id) DO UPDATE SET
         firmenname = EXCLUDED.firmenname,
         stadt = EXCLUDED.stadt,
         plz = EXCLUDED.plz,
         branche = EXCLUDED.branche,
         ausbildungsberufe = EXCLUDED.ausbildungsberufe,
         match_umkreis = EXCLUDED.match_umkreis,
         beschreibung = EXCLUDED.beschreibung,
         website = EXCLUDED.website,
         updated_at = CURRENT_TIMESTAMP
       RETURNING *`,
      [req.user.id, firmenname, stadt, plz, branche, ausbildungsberufe, match_umkreis ?? 25, beschreibung, website]
    );

    return res.json({ profile: result.rows[0] });
  } catch (err) {
    console.error('[firm/profile PUT]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht gespeichert werden.' });
  }
});

export default router;
