import { Router } from 'express';
import pool from '../db.mjs';
import { requireAuth } from '../auth.mjs';

const router = Router();

// Sicherstellen, dass die student_profiles-Tabelle existiert
async function ensureTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(320) NOT NULL UNIQUE,
      password TEXT NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'firm')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS student_profiles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      name VARCHAR(200),
      stadt VARCHAR(200),
      plz VARCHAR(10),
      schulabschluss VARCHAR(100),
      beruf VARCHAR(200),
      match_umkreis INTEGER DEFAULT 25,
      sprachen TEXT,
      hinweis TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

ensureTable().catch((err) => console.error('[student_profiles] Tabelle konnte nicht angelegt werden:', err.message));

// GET /api/student/profile
router.get('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'student') {
    return res.status(403).json({ error: 'Nur fuer Bewerbende zugaenglich.' });
  }

  try {
    await ensureTable();

    const result = await pool.query(
      'SELECT * FROM student_profiles WHERE user_id = $1',
      [req.user.id]
    );
    return res.json({ profile: result.rows[0] ?? null });
  } catch (err) {
    console.error('[student/profile GET]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht geladen werden.' });
  }
});

// PUT /api/student/profile
router.put('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'student') {
    return res.status(403).json({ error: 'Nur fuer Bewerbende zugaenglich.' });
  }

  const { name, stadt, plz, schulabschluss, beruf, match_umkreis, sprachen, hinweis } = req.body ?? {};

  try {
    await ensureTable();

    const result = await pool.query(
      `INSERT INTO student_profiles (user_id, name, stadt, plz, schulabschluss, beruf, match_umkreis, sprachen, hinweis, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, CURRENT_TIMESTAMP)
       ON CONFLICT (user_id) DO UPDATE SET
         name = EXCLUDED.name,
         stadt = EXCLUDED.stadt,
         plz = EXCLUDED.plz,
         schulabschluss = EXCLUDED.schulabschluss,
         beruf = EXCLUDED.beruf,
         match_umkreis = EXCLUDED.match_umkreis,
         sprachen = EXCLUDED.sprachen,
         hinweis = EXCLUDED.hinweis,
         updated_at = CURRENT_TIMESTAMP
       RETURNING *`,
      [req.user.id, name, stadt, plz, schulabschluss, beruf, match_umkreis ?? 25, sprachen, hinweis]
    );

    return res.json({ profile: result.rows[0] });
  } catch (err) {
    console.error('[student/profile PUT]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht gespeichert werden.' });
  }
});

export default router;
