import { Router } from 'express';
import pool from '../db.mjs';
import { requireAuth } from '../auth.mjs';

const router = Router();

const ALLOWED_MATCH_RADIUS_VALUES = new Set([5, 10, 25, 50, 100]);

function normalizeMatchRadiusForStorage(value) {
  const normalized = String(value ?? '').trim().toLowerCase();
  if (!normalized) {
    return 25;
  }
  if (normalized === 'de' || normalized === 'deutschlandweit') {
    return null;
  }

  const parsed = Number.parseInt(normalized, 10);
  if (Number.isFinite(parsed) && ALLOWED_MATCH_RADIUS_VALUES.has(parsed)) {
    return parsed;
  }

  return 25;
}

// Sicherstellen, dass die student_profiles-Tabelle existiert
let _ensureTablePromise = null;
async function ensureTable() {
  if (_ensureTablePromise) return _ensureTablePromise;
  _ensureTablePromise = _runEnsureTable().catch((err) => {
    _ensureTablePromise = null;
    throw err;
  });
  return _ensureTablePromise;
}
async function _runEnsureTable() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(320) NOT NULL UNIQUE,
      password TEXT NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'firm')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS student_profiles (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
      name VARCHAR(200),
      stadt VARCHAR(200),
      plz VARCHAR(10),
      schulabschluss VARCHAR(100),
      beruf VARCHAR(200),
      match_umkreis INTEGER DEFAULT 25,
      sprachen TEXT,
      hinweis TEXT,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Erweiterte Felder – werden per ALTER TABLE IF NOT EXISTS ergänzt
  const extraCols = [
    'kurzprofil_einzeiler TEXT',
    'besondere_faehigkeiten TEXT',
    'abgeschlossene_ausbildung TEXT',
    'behinderung VARCHAR(100)',
    'behinderungs_art VARCHAR(200)',
    'behinderungs_grad VARCHAR(50)',
    'grundschule_von VARCHAR(20)',
    'grundschule_bis VARCHAR(20)',
    'weiterfuehrende_von VARCHAR(20)',
    'weiterfuehrende_schulform VARCHAR(100)',
    'weiterfuehrende_bis VARCHAR(20)',
    'wahlfach VARCHAR(100)',
    'note_mathe VARCHAR(10)',
    'note_deutsch VARCHAR(10)',
    'note_englisch VARCHAR(10)',
    'note_wahlfach VARCHAR(10)',
    'profilbid VARCHAR(30)',
    'profil_code VARCHAR(20)',
    'verified BOOLEAN DEFAULT FALSE',
    'registrierung_abgeschlossen BOOLEAN DEFAULT FALSE',
    'vollprofil_freigegeben BOOLEAN DEFAULT FALSE',
    'user_email VARCHAR(320)',
    'berufswunsch VARCHAR(200)',
  ];
  for (const col of extraCols) {
    await pool.query(`ALTER TABLE student_profiles ADD COLUMN IF NOT EXISTS ${col}`).catch(() => {});
  }
}

ensureTable().catch((err) => console.error('[student_profiles] Tabelle konnte nicht angelegt werden:', err.message));

// GET /api/student/profile
router.get('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'student') {
    return res.status(403).json({ error: 'Nur fuer Bewerbende zugaenglich.' });
  }

  try {
    await ensureTable();

    const result = await pool.query(
      'SELECT * FROM student_profiles WHERE user_id = $1',
      [req.user.id]
    );
    return res.json({ profile: result.rows[0] ?? null });
  } catch (err) {
    console.error('[student/profile GET]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht geladen werden.' });
  }
});

// PUT /api/student/profile
router.put('/profile', requireAuth, async (req, res) => {
  if (req.user.role !== 'student') {
    return res.status(403).json({ error: 'Nur fuer Bewerbende zugaenglich.' });
  }

  const {
    name, stadt, plz, schulabschluss, beruf, match_umkreis, sprachen, hinweis,
    kurzprofil_einzeiler, besondere_faehigkeiten, abgeschlossene_ausbildung,
    behinderung, behinderungs_art, behinderungs_grad,
    grundschule_von, grundschule_bis, weiterfuehrende_von, weiterfuehrende_schulform, weiterfuehrende_bis,
    wahlfach, note_mathe, note_deutsch, note_englisch, note_wahlfach,
    profilbid, profil_code, registrierung_abgeschlossen, vollprofil_freigegeben, user_email, berufswunsch,
  } = req.body ?? {};

  const normalizedMatchRadius = normalizeMatchRadiusForStorage(match_umkreis);

  try {
    await ensureTable();

    const result = await pool.query(
      `INSERT INTO student_profiles (
         user_id, name, stadt, plz, schulabschluss, beruf, match_umkreis, sprachen, hinweis,
         kurzprofil_einzeiler, besondere_faehigkeiten, abgeschlossene_ausbildung,
         behinderung, behinderungs_art, behinderungs_grad,
         grundschule_von, grundschule_bis, weiterfuehrende_von, weiterfuehrende_schulform, weiterfuehrende_bis,
         wahlfach, note_mathe, note_deutsch, note_englisch, note_wahlfach,
         profilbid, profil_code, registrierung_abgeschlossen, vollprofil_freigegeben, user_email, berufswunsch,
         updated_at
       )
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,CURRENT_TIMESTAMP)
       ON CONFLICT (user_id) DO UPDATE SET
         name = EXCLUDED.name,
         stadt = EXCLUDED.stadt,
         plz = EXCLUDED.plz,
         schulabschluss = EXCLUDED.schulabschluss,
         beruf = EXCLUDED.beruf,
         match_umkreis = EXCLUDED.match_umkreis,
         sprachen = EXCLUDED.sprachen,
         hinweis = EXCLUDED.hinweis,
         kurzprofil_einzeiler = EXCLUDED.kurzprofil_einzeiler,
         besondere_faehigkeiten = EXCLUDED.besondere_faehigkeiten,
         abgeschlossene_ausbildung = EXCLUDED.abgeschlossene_ausbildung,
         behinderung = EXCLUDED.behinderung,
         behinderungs_art = EXCLUDED.behinderungs_art,
         behinderungs_grad = EXCLUDED.behinderungs_grad,
         grundschule_von = EXCLUDED.grundschule_von,
         grundschule_bis = EXCLUDED.grundschule_bis,
         weiterfuehrende_von = EXCLUDED.weiterfuehrende_von,
         weiterfuehrende_schulform = EXCLUDED.weiterfuehrende_schulform,
         weiterfuehrende_bis = EXCLUDED.weiterfuehrende_bis,
         wahlfach = EXCLUDED.wahlfach,
         note_mathe = EXCLUDED.note_mathe,
         note_deutsch = EXCLUDED.note_deutsch,
         note_englisch = EXCLUDED.note_englisch,
         note_wahlfach = EXCLUDED.note_wahlfach,
         profilbid = EXCLUDED.profilbid,
         profil_code = EXCLUDED.profil_code,
         registrierung_abgeschlossen = EXCLUDED.registrierung_abgeschlossen,
         vollprofil_freigegeben = EXCLUDED.vollprofil_freigegeben,
         user_email = EXCLUDED.user_email,
         berufswunsch = EXCLUDED.berufswunsch,
         updated_at = CURRENT_TIMESTAMP
       RETURNING *`,
      [
        req.user.id, name, stadt, plz, schulabschluss, beruf, normalizedMatchRadius, sprachen, hinweis,
        kurzprofil_einzeiler ?? null, besondere_faehigkeiten ?? null, abgeschlossene_ausbildung ?? null,
        behinderung ?? null, behinderungs_art ?? null, behinderungs_grad ?? null,
        grundschule_von ?? null, grundschule_bis ?? null, weiterfuehrende_von ?? null, weiterfuehrende_schulform ?? null, weiterfuehrende_bis ?? null,
        wahlfach ?? null, note_mathe ?? null, note_deutsch ?? null, note_englisch ?? null, note_wahlfach ?? null,
        profilbid ?? null, profil_code ?? null, registrierung_abgeschlossen ?? false, vollprofil_freigegeben ?? false,
        user_email ?? null, berufswunsch ?? null,
      ]
    );

    return res.json({ profile: result.rows[0] });
  } catch (err) {
    console.error('[student/profile PUT]', err.message);
    return res.status(500).json({ error: 'Profil konnte nicht gespeichert werden.' });
  }
});

export default router;
