-- AzubiMatch PostgreSQL Setup
-- Ausfuehren mit: psql -U postgres -p 5432 -f setup.sql

-- Datenbank anlegen (wird uebersprungen wenn sie schon existiert)
SELECT 'CREATE DATABASE azubimatch ENCODING ''UTF8'' TEMPLATE template0'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'azubimatch')\gexec

\connect azubimatch

-- App-Benutzer anlegen
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'azubimatch_app') THEN
        CREATE ROLE azubimatch_app LOGIN PASSWORD 'AzubiMatch_DB_2026!';
    END IF;
END
$$;

-- users-Tabelle
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(190) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'student' CHECK (role IN ('student', 'firm')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index fuer schnelle E-Mail-Suche beim Login
CREATE INDEX IF NOT EXISTS users_email_idx ON users (email);

-- Rechte fuer App-Benutzer
GRANT CONNECT ON DATABASE azubimatch TO azubimatch_app;
GRANT USAGE, CREATE ON SCHEMA public TO azubimatch_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO azubimatch_app;
GRANT REFERENCES ON TABLE users TO azubimatch_app;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO azubimatch_app;

CREATE TABLE IF NOT EXISTS student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(200),
    stadt VARCHAR(200),
    plz VARCHAR(10),
    schulabschluss VARCHAR(100),
    beruf VARCHAR(200),
    match_umkreis INTEGER DEFAULT 25,
    sprachen TEXT,
    hinweis TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS firm_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    firmenname VARCHAR(200),
    stadt VARCHAR(200),
    plz VARCHAR(10),
    branche VARCHAR(200),
    ausbildungsberufe TEXT,
    match_umkreis INTEGER DEFAULT 25,
    beschreibung TEXT,
    website VARCHAR(500),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

GRANT SELECT, INSERT, UPDATE, DELETE ON student_profiles, firm_profiles TO azubimatch_app;
GRANT USAGE, SELECT ON student_profiles_id_seq, firm_profiles_id_seq TO azubimatch_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO azubimatch_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO azubimatch_app;

SELECT 'Setup abgeschlossen. Tabellen und Benutzer sind bereit.' AS status;
